


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author farel
 */
public class pn_man extends javax.swing.JPanel {

    /**
     
     */
    public pn_man() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_blazer = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        bt_blz = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pn_sherpa = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        bt_sherpa = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pn_jacktetvintage = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        bt_jacket = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pn_carhartpants = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        bt_carhart = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_blazer.setBackground(new java.awt.Color(153, 153, 153));
        pn_blazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_blazerMouseClicked(evt);
            }
        });
        pn_blazer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/88820d12bfab24b3058c2dde7a6a057d (2).jpeg"))); // NOI18N
        pn_blazer.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        bt_blz.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bt_blz.setText("Blazers");
        bt_blz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_blzMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_blzMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_blzMouseExited(evt);
            }
        });
        pn_blazer.add(bt_blz, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        jLabel27.setText("500K");
        pn_blazer.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 20));

        add(pn_blazer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pn_sherpa.setBackground(new java.awt.Color(153, 153, 153));
        pn_sherpa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2de990ce-cfd2-497d-a2c2-e9bdb2f25b07.jpg"))); // NOI18N
        pn_sherpa.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bt_sherpa.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bt_sherpa.setText("Sherpa Zara");
        bt_sherpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_sherpaMouseClicked(evt);
            }
        });
        pn_sherpa.add(bt_sherpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel30.setText("200k");
        pn_sherpa.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        add(pn_sherpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        pn_jacktetvintage.setBackground(new java.awt.Color(153, 153, 153));
        pn_jacktetvintage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/jaket_vintage_thrift_preloved__1661350058_99878c7f_progressive.jpg"))); // NOI18N
        pn_jacktetvintage.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 170));

        bt_jacket.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bt_jacket.setText(" Jacket Vintage");
        bt_jacket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_jacketMouseClicked(evt);
            }
        });
        pn_jacktetvintage.add(bt_jacket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel33.setText("200K");
        pn_jacktetvintage.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        add(pn_jacktetvintage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 240));

        pn_carhartpants.setBackground(new java.awt.Color(153, 153, 153));
        pn_carhartpants.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carhartt-thrift-bermuda-leaf-stonewashed-p6354-4736_image.jpg"))); // NOI18N
        pn_carhartpants.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 175));

        bt_carhart.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bt_carhart.setText("Carhart Pants");
        bt_carhart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_carhartMouseClicked(evt);
            }
        });
        pn_carhartpants.add(bt_carhart, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel36.setText("700k");
        pn_carhartpants.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 30));

        add(pn_carhartpants, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_blzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_blzMouseClicked
     
       
        this.setVisible(false);
        new Penjualan1() .setVisible(true);
    }//GEN-LAST:event_bt_blzMouseClicked

    private void bt_blzMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_blzMouseEntered
     
    }//GEN-LAST:event_bt_blzMouseEntered

    private void bt_blzMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_blzMouseExited
       
    }//GEN-LAST:event_bt_blzMouseExited

    private void pn_blazerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_blazerMouseClicked

    }//GEN-LAST:event_pn_blazerMouseClicked

    private void bt_sherpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sherpaMouseClicked
   this.setVisible(false);
        new Penjualan1() .setVisible(true);
    }//GEN-LAST:event_bt_sherpaMouseClicked

    private void bt_jacketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_jacketMouseClicked
      this.setVisible(false);
        new Penjualan1() .setVisible(true);
    }//GEN-LAST:event_bt_jacketMouseClicked

    private void bt_carhartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_carhartMouseClicked
        this.setVisible(false);
        new Penjualan1() .setVisible(true);
    }//GEN-LAST:event_bt_carhartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_blz;
    private javax.swing.JLabel bt_carhart;
    private javax.swing.JLabel bt_jacket;
    private javax.swing.JLabel bt_sherpa;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel pn_blazer;
    private javax.swing.JPanel pn_carhartpants;
    private javax.swing.JPanel pn_jacktetvintage;
    private javax.swing.JPanel pn_sherpa;
    // End of variables declaration//GEN-END:variables
}
